env = Environment()

env.Append(CPPFLAGS = Split('-std=c++11'))
env.Append(CPPPATH = [Dir('../../firmware/common')])

# libraries
libraries = Split('libusb-1.0 log4cpp')

for lib in libraries:
	env.ParseConfig('pkg-config %s --cflags --libs' % lib)

binary_name = 'szark_server'
build_dir = 'build'

env.VariantDir(build_dir + '/src', 'src')
env.VariantDir(build_dir + '/test', 'test')

commonObjectFiles = env.Object([f for f in Glob(build_dir + '/src/*.cpp') if 'main.cpp' not in f.path])

env.Program(build_dir + '/' + binary_name, commonObjectFiles + [build_dir + '/src/main.cpp'])

testEnv = env.Clone()
testEnv['CPPPATH'].append('./test/')
testEnv['CPPPATH'].append('./src/')
testEnv['LIBS'].append('boost_unit_test_framework')

# here I append all needed object files
testObjectFiles = Glob(build_dir + '/test/*.cpp')
testEnv.Program(build_dir + '/' + binary_name + '_test', testObjectFiles + commonObjectFiles)

# vim: set ft=python
