/*
 * delay.cpp
 *
 *  Created on: 10-08-2013
 *      Author: michal
 */

#include "global.h"

#include <avr/io.h>
#include <util/delay.h>

#include "delay.h"

void delay::wait100us() {
	// Generated by delay loop calculator
	// at http://www.bretmulvey.com/avrdelay.html
	//
	// Delay 1 920 cycles
	// 120us at 16 MHz

	asm volatile (
		"    ldi  r18, 3" "\n"
		"    ldi  r19, 125" "\n"
		"1:  dec  r19" "\n"
		"    brne 1b" "\n"
		"    dec  r18" "\n"
		"    brne 1b" "\n"
		"    rjmp 1f" "\n"
		"1:" "\n"
	);
}

void delay::waitMs(uint8_t milliseconds) {
	for (uint8_t i = 0; i < milliseconds; i++) {
		_delay_ms(1);
	}
}

