#ifndef _USB_SETTINGS_
#define _USB_SETTINGS_

#define USB_SETTINGS_VENDOR_ID 0x03eb
#define USB_SETTINGS_DEVICE_ID 0x206c

#define USB_SETTINGS_VENDOR_NAME "slomkowski.eu"
#define USB_SETTINGS_DEVICE_NAME "SZARK Robot Bridge"

#define USB_SETTINGS_HOST_TO_DEVICE_ENDPOINT_NO 1
#define USB_SETTINGS_HOST_TO_DEVICE_DATAPACKET_SIZE 128

#define USB_SETTINGS_DEVICE_TO_HOST_ENDPOINT_NO 2
#define USB_SETTINGS_DEVICE_TO_HOST_DATAPACKET_SIZE 64

#endif
